"""Transfer learning: regime identification, metrics, TransWeave mapping."""

from .regime import fit_hmm_regime, fit_regime_all_assets, load_regime_result
from .transweave import (
    SimpleJDModel,
    TransferMap,
    compute_time_change,
    evaluate_direct,
    evaluate_scratch,
    evaluate_transfer,
    finetune_transfer_map,
    infer_weak_theta,
    run_transfer_experiment,
    train_transfer_map,
    train_weak_target_model,
    upsample_regime_to_15min,
)
from .metrics import (
    compute_v_j,
    compute_w_jd,
    compute_w2_jump,
    compute_w_crit,
    compute_rho_regime,
    compute_s_transfer,
    compute_rolling_w_jd,
    spectral_transfer_condition,
    time_change_diagnostic,
    time_change_diagnostic_from_sequences,
    make_transfer_decision,
    regime_diagnostics,
)
from .feature_shift import compute_feature_shift, compute_s_transfer_adjusted

__all__ = [
    "SimpleJDModel",
    "TransferMap",
    "compute_time_change",
    "evaluate_direct",
    "evaluate_scratch",
    "evaluate_transfer",
    "finetune_transfer_map",
    "infer_weak_theta",
    "run_transfer_experiment",
    "train_transfer_map",
    "train_weak_target_model",
    "upsample_regime_to_15min",
    "fit_hmm_regime",
    "fit_regime_all_assets",
    "load_regime_result",
    "compute_v_j",
    "compute_w_jd",
    "compute_w2_jump",
    "compute_w_crit",
    "compute_rho_regime",
    "compute_s_transfer",
    "spectral_transfer_condition",
    "time_change_diagnostic",
    "time_change_diagnostic_from_sequences",
    "compute_rolling_w_jd",
    "make_transfer_decision",
    "regime_diagnostics",
    "compute_feature_shift",
    "compute_s_transfer_adjusted",
]
